const def = {
  BC: "Patches",
  BL: "Blowing",
  BR: "Mist",
  DR: "Low Drifting",
  DS: "Dust Storm",
  DU: "Dust",
  DZ: "Drizzle",
  FG: "Fog",
  FU: "Smoke",
  FZ: "Freezing",
  GR: "Hail",
  GS: "Small Hail/Snow Pellets",
  HZ: "Haze",
  IC: "Ice Crystals",
  MI: "Shallow",
  PL: "Ice Pellets",
  PO: "Well-Developed Dust/Sand Whirls",
  PR: "Partial",
  PY: "Spray",
  RA: "Rain",
  SA: "Sand",
  SG: "Snow",
  SH: "Showers",
  SN: "Snow",
  SQ: "Squalls",
  SS: "Sandstorm",
  TS: "Thunderstorm",
  UP: "Unknown Precipitation",
  VA: "Volcanic Ash",
  VC: "In the vicinity",
  modifiers: {
    "-": "Light",
    "+": "Heavy",
    P: "More Than",
    M: "Less than",
    B: "Began",
    E: "Ended",
  },
  clouds: {
    CLR: "Clear at or below 12,000 AGL",
    FEW: "Few",
    SCT: "Scattered",
    BKN: "Broken",
    SKC: "Sky Clear",
    TCU: "Tower Cumulus",
    CB: "Cumulonimbus",
  },
  other: {
    A01: "Automated Observation without precipitation discrimination",
    A01: "Automated Observation with precipitation discrimination",
    A: "Altimeter",
    AMD: "Amended Forecast",
    AUTO: "Without Human editing",
    BECMG: "Becoming",
    CAVU: "Ceiling and visibility unlimited",
    COR: "Correction",
    DSNT: "Distant weather phenomenon",
    FM: "From",
    FROPA: "Frontal Passage",
    LTG: "Lightning",
    LDG: "Landing",
    M: "Minus",
    NO: "Not available",
    NSW: "No signinficant weather",
    P: "Plus",
    PRESFR: "Pressure falling rapidly",
    PRESRR: "Pressure rising rapidly",
    PROB: "Probability",
    R: "Runway",
    RWY: "Runway",
    RVRNO: "Runway visual range not available",
    SFC: "Surface",
    SLP: "Sea level pressure",
    SLPNO: "Sea level pressure not available",
    SM: "Statute miles",
    SPECI: "Special report",
    TEMPO: "Temporarily",
    T: "Temp",
    TWR: "Tower",
    V: "Varying",
    VIRGA: "Virga",
    VRB: "Variable",
    VIS: "Visibility",
    VV: "Indefinite vertical visibility",
    WS: "Wind shear",
    WSHFT: "Wind shift"
  }
}

module.exports = def;